from typing import Literal, Protocol

from playlist_downloader.models.playlist import Track
from playlist_downloader.models.download_artifact import DownloadArtifact
from playlist_downloader.models.scored_candidate import ScoredCandidate
from playlist_downloader.models.download_summary import DownloadSummary

class DownloadReporter(Protocol):
    def on_collection_start(self, label: str, total_tracks: int) -> None: ...
    def on_track_start(self, index: int, total_tracks: int, track: Track) -> None: ...
    def on_track_skipped(self, index: int, total_tracks: int, track: Track, artifact: DownloadArtifact) -> None: ...
    def on_track_success(self, index: int, total_tracks: int, track: Track, artifact: DownloadArtifact) -> None: ...
    def on_track_failure(self, index: int, total_tracks: int, track: Track, error: str) -> None: ...
    def on_track_unresolved(self, index: int, total_tracks: int, track: Track, message: str) -> None: ...
    def review_candidate(
        self,
        track: Track,
        candidate_index: int,
        total_candidates: int,
        scored_candidate: ScoredCandidate,
    ) -> Literal["download", "next", "skip", "abort"]: ...
    def on_collection_finished(self, summary: "DownloadSummary") -> None: ...